name: my_clock
description: "Simple clock app"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.4.0
  dynamic_color: ^1.8.1
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4 
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_monochrome: "assets/icon/icon_monochrome.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Aktura
      fonts:
        - asset: fonts/Aktura-Regular.otf
          weight: 700
    - family: Array
      fonts:
        - asset: fonts/Array-Regular.otf
          weight: 700
    - family: Gambarino
      fonts:
        - asset: fonts/Gambarino-Regular.otf
          weight: 700
    - family: Melodrama
      fonts:
        - asset: fonts/Melodrama-Bold.otf
          weight: 700
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-ExtraBold.otf
          weight: 700
    - family: Stardom
      fonts:
        - asset: fonts/Stardom-Regular.otf
          weight: 700
        
          